### ISSUE TITLE
Issue when compress GEOJSON

### ISSUE THREAD

**Issue by nawwa** [dwilhelm89/compress-geojson#2]
Hello,

When i compress a GeoJson like this : 
  { 
    "type": "LineString",
    "coordinates": [ [100.0, 0.0, 5,5], [101.0, 1.0, 4,6] ]
    }
The decompression is false because i lost some data, i get : 
  { 
       "type": "LineString",
       "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]
    }

As you can see i lost my third value... 

Thanks

**Comment by dwilhelm89** [comment]
Hi,
interesting. I don't know why 3D coordinates do not work.
However, I wouldn't even recommend using this library for production use cases as it is way too slow and doesn't even have that much of an impact. This project was more or less only for done for research purposes.

If you really do need to compress your Geojson, you might be better of with:
https://github.com/igorti/geojson-minifier

**Comment by nawwa** [comment]
Thanks dude !
